import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  // button
  const CalcButton: React.FC<{
    content: string;
    color?: string;
    bgColor?: string;
    width?: string;
  }> = ({
    content,
    bgColor = "bg-gray-200",
    color = "text-black",
    width = "w-20",
  }) => {
    return (
      <button
        className={`flex justify-center items-center p-4 text-xl font-light h-20 ${width} ${bgColor} ${color} `}
      >
        {content}
      </button>
    );
  };

  const numbers = [7, 8, 9, 4, 5, 6, 1, 2, 3, 0, "."];
  const operators = ["C", "+/-", "%", "/", "x", "-", "+", "="];

  return (
    <>
      <Head>
        <title>Integral - UX Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen justify-center items-center">
        {/* display section  */}

        <div className="w-80  flex flex-col">
          <div className="flex justify-end items-center text-xl font-light w-full py-8">
            0
          </div>

          <div className="flex">
            <div className="flex flex-col divide-x-1 divide-gray-700">
              <div className="flex ">
                {operators.slice(0, 3).map((operator) => {
                  return (
                    <div key={operator}>
                      <CalcButton content={operator} bgColor="bg-gray-500" />
                    </div>
                  );
                })}
              </div>

              <div className="flex">
                {numbers.slice(0, 3).map((number) => {
                  return (
                    <div key={number}>
                      <CalcButton content={number.toString()} />
                    </div>
                  );
                })}
              </div>

              <div className="flex">
                {numbers.slice(3, 6).map((number) => {
                  return (
                    <div key={number}>
                      <CalcButton content={number.toString()} />
                    </div>
                  );
                })}
              </div>

              <div className="flex">
                {numbers.slice(6, 9).map((number) => {
                  return (
                    <div key={number}>
                      <CalcButton content={number.toString()} />
                    </div>
                  );
                })}
              </div>

              <div className="grid grid-cols-3">
                <div className="col-span-2">
                  <CalcButton width="w-full" content={numbers[9].toString()} />
                </div>
                <div className="col-span-1">
                  <CalcButton content={numbers[10].toString()} />
                </div>
              </div>
            </div>

            {/* operators   */}
            <div className="flex flex-col">
              {operators.slice(3).map((operator) => {
                return (
                  <div key={operator}>
                    <CalcButton
                      content={operator}
                      bgColor="bg-yellow-600"
                      color="text-white"
                    />
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
